<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GitExtensions.Extensibility\GitExtensions.Extensibility.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Settings\UserControls\CredentialsControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>

</Project>
